### ISSUE TITLE
Code eval with ~ doesn't work if 'nowrapscan' is enabled.

### ISSUE THREAD

**Issue by Carpetsmoker** [KeyboardFire/vim-minisnip#1] opened 2017-05-05 13:02 UTC
I have this `~/.vim/minisnip/_go_pkg` file:

    package {{+~expand('%:p:h:t')+}}

However, when pressing `pkg<Tab>` in a new empty buffer it gets replaced by exactly that text, instead of the expected `package dirname`.

I narrowed down the problem to the `nowrapscan` setting; If I remove `set nowrapscan` from my `~/.vimrc` it works as expected.

**Comment by LemonBoy** [comment] 2017-05-05 13:46
It is probably due to the lack of the explicit 'W' option [here](https://github.com/KeyboardFire/vim-minisnip/blob/47e28561e327c13d9cbe62a7bc9cd610eb670130/plugin/vim-minisnip.vim#L30) as the help for `search()` states:

> If neither 'w' or 'W' is given, the 'wrapscan' option applies

**Comment by KeyboardFire** [comment] 2017-05-06 15:10
This is actually due to a bug in vim, which I [have just reported](https://github.com/vim/vim/issues/1683).

**Comment by Carpetsmoker** [comment] 2017-05-06 16:03
Thanks ;-) Using `gn` twice seems to work by the way, so for now I've just added this workaround:

```
diff --git i/plugin/vim-minisnip.vim w/plugin/vim-minisnip.vim
index f211401..1af2dc7 100644
--- i/plugin/vim-minisnip.vim
+++ w/plugin/vim-minisnip.vim
@@ -60,7 +60,12 @@ function! s:SelectPlaceholder()
     "   when a snippet begins with a placeholder)
     " we also use keeppatterns to avoid clobbering the search history /
     "   highlighting all the other placeholders
-    keeppatterns execute 'normal! /' . s:delimpat . "/e\<cr>gn\"sy"
+    if &wrapscan
+        keeppatterns execute 'normal! /' . s:delimpat . "/e\<cr>gn\"sy"
+       " Workaround for https://github.com/KeyboardFire/vim-minisnip/issues/1
+    else
+        keeppatterns execute 'normal! /' . s:delimpat . "/e\<cr>gngn\"sy"
+    endif
 
     " save the contents of the previous placeholder (for backrefs)
     call add(s:placeholder_texts, s:placeholder_text)
```

**Comment by arp242** [comment] 2017-06-27 05:53
Fixed in https://github.com/vim/vim/commit/add8dce38de65a0c64e8f54d6bdcadb45a8de2cf – confirmed it worked in Vim  8.0.628

**Closed by arp242** 2017-06-27 05:53 UTC
